version: 2.1

executors:
  my-executor:
    docker:
      - image: circleci/node:12.20.2
    working_directory: ~/repo

jobs:
  build:
    executor: my-executor

    steps:
      - checkout
      - run: 
          name: clean cache
          command: npm cache clean --force
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: install
          command: npm ci
      - run:
          name: npm install
          command: npm install
      - run:
          name: build
          command: npm run-script build

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
            - ~/.npm
            - ~/.cache
          key: v1-dependencies-{{ checksum "package.json" }}
      - store_artifacts:
          path: build
          destination: BuildResult

workflows:
  version: 2.1
  workflow:
    jobs:
      - build
